USE [master]
GO

/****** Object:  Database [Phonebook]    Script Date: 05/29/2018 10:32:39 ******/
CREATE DATABASE [Phonebook] ON  PRIMARY 
( NAME = N'Phonebook', FILENAME = N'C:\Phonebook.mdf' , SIZE = 5000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Phonebook_log', FILENAME = N'C:\Phonebook_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Phonebook] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Phonebook].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Phonebook] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Phonebook] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Phonebook] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Phonebook] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Phonebook] SET ARITHABORT OFF 
GO

ALTER DATABASE [Phonebook] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Phonebook] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Phonebook] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Phonebook] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Phonebook] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Phonebook] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Phonebook] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Phonebook] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Phonebook] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Phonebook] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Phonebook] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Phonebook] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Phonebook] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Phonebook] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Phonebook] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Phonebook] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Phonebook] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Phonebook] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Phonebook] SET  READ_WRITE 
GO

ALTER DATABASE [Phonebook] SET RECOVERY FULL 
GO

ALTER DATABASE [Phonebook] SET  MULTI_USER 
GO

ALTER DATABASE [Phonebook] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Phonebook] SET DB_CHAINING OFF 
GO


SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ContactNumber](
	[ContactNumberID] [int] NOT NULL identity(1, 1),
	[ContactID] [int] NOT NULL,
	[NumberType] [int] NULL,
	[Number] [nvarchar](150) NULL,
	[Deleted] [bit] NULL,
	[DateCreated] [datetime] NULL,
	[DateModified] [datetime] NULL,
 CONSTRAINT [PK_ContactNumberID] PRIMARY KEY CLUSTERED 
(
	[ContactNumberID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[NumberType](
	[NumberTypeID] [int] IDENTITY(1,1) NOT NULL,
	[NumberName] [nvarchar](50) NULL,
	[NumberLimit] [int] NULL,
	[Deleted] [bit] NULL,
	[DateCreated] [datetime] NULL,
	[DateModified] [datetime] NULL,
 CONSTRAINT [PK_NumberType] PRIMARY KEY CLUSTERED 
(
	[NumberTypeID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Relationship](
	[RelationshipID] [int] IDENTITY(1,1) NOT NULL,
	[RelationshipName] [nvarchar](50) NOT NULL,
	[Deleted] [bit] NULL,
	[DateCreated] [datetime] NULL,
	[DateModified] [datetime] NULL,
 CONSTRAINT [PK_Relationship] PRIMARY KEY CLUSTERED 
(
	[RelationshipID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Contact](
	[ContactID] [int] IDENTITY(1,1) NOT NULL,
	[ContactName] [nvarchar](150) NULL,
	[ContactSurname] [nvarchar](150) NULL,
	[Relationship] [int] NULL,
	[Deleted] [bit] NULL,
	[DateCreated] [datetime] NULL,
	[DateModified] [datetime] NULL,
 CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED 
(
	[ContactID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

